name: Deploy

on:
  workflow_dispatch:
    inputs:
      network:
        description: "Network"
        required: true
      version:
        description: "Version"
        default: ""

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.version }}
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - run: echo ${{ github.event.inputs.network }}
