name: Main

on:
  push:
    tags-ignore: [v*.*.*]
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: yarn install --frozen-lockfile
      - run: yarn format:check
      - run: yarn lint:solhint
      - run: yarn lint:eslint
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - run: yarn test
      - run: echo check code coverage
  performance:
    runs-on: ubuntu-latest
    steps:
      - run: echo check deployment costs
      - run: echo check average gas usage
  security:
    runs-on: ubuntu-latest
    steps:
      - run: echo run slither
      - run: echo run manticore
      - run: echo run echidna
  integration:
    runs-on: ubuntu-latest
    needs: [lint, test, performance, security]
    steps:
      - run: echo deploy contracts on ropsten
      - run: echo verify etherscan source code
      - run: echo run integration tests
  publish:
    runs-on: ubuntu-latest
    needs: [integration]
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PEEWEE_TOKEN }}
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: yarn install --frozen-lockfile
      - run: git config --global user.email mr@pee.wee && git config --global user.name peewee
      - run: yarn version --patch --message "Increment patch version [skip ci]"
      - run: git push --follow-tags

      - run: yarn config set registry https://registry.npmjs.org
      - run: yarn config set _auth ${{ secrets.NPM_TOKEN }}
      - run: npm publish

      - run: yarn config set registry https://npm.pkg.github.com
      - run: yarn config set _auth ${{ secrets.GITHUB_TOKEN }}
      - run: yarn publish
