name: Main

on:
  push:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: echo build and publish Docker image
  lint:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: echo
        run: echo run formatter and linters
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: echo
        run: echo run unit tests and gas tests
  scan:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: echo
        run: echo run slither, manticore and echidna
  integration:
    runs-on: ubuntu-latest
    needs: [lint, test, scan]
    steps:
      - name: echo
        run: echo deploy contracts on ropsten and run integration tests
  publish:
    runs-on: ubuntu-latest
    needs: [integration]
    steps:
      - name: echo
        run: echo increment semver, tag commit, publish package to npm and github
