name: Main

on:
  push:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: conf/Dockerfile
          tags: bidin/namespace-ci
          push: true
  lint:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: echo
        run: echo run formatter and linters
  test:
    runs-on: ubuntu-latest
    needs: build
    container: bidin/namespace-ci
    steps:
      - name: Run unit tests
        run: yarn test
  security:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: echo
        run: echo run slither, manticore and echidna
  integration:
    runs-on: ubuntu-latest
    needs: [lint, test, security]
    steps:
      - name: echo
        run: echo deploy contracts on ropsten and run integration tests
  publish:
    runs-on: ubuntu-latest
    needs: [integration]
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - name: echo
        run: echo increment semver, tag commit, publish package to npm and github
