name: Main

on:
  push:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - run: yarn install --frozen-lockfile
      - run: yarn format:check
      - run: yarn lint:solhint
      - run: yarn lint:eslint
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - run: yarn test
  performance:
    runs-on: ubuntu-latest
    steps:
      - run: echo check deployment costs
      - run: echo check average gas usage
  security:
    runs-on: ubuntu-latest
    steps:
      - run: echo run slither
      - run: echo run manticore
      - run: echo run echidna
      - run: echo what about mythx?
  integration:
    runs-on: ubuntu-latest
    needs: [lint, test, performance, security]
    steps:
      - run: echo deploy contracts on ropsten
      - run: echo verify etherscan source code
      - run: echo run integration tests
  publish:
    runs-on: ubuntu-latest
    needs: [integration]
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - run: echo increment semver
      - run: echo tag commit
      - run: echo push commit and tag
      - run: echo publish package to npm
      - run: echo publish package to github
