name: Main

on:
  push:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: echo build and publish Docker image
  lint:
    runs-on: ${{}}
    needs: build
    steps:
      - name: echo
        run: echo run formatter and linters
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: echo
        run: echo run unit and gas tests
  security:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: echo
        run: echo run slither, manticore and echidna
  deployment:
    runs-on: ubuntu-latest
    needs: [lint, test, security]
    steps:
      - name: echo
        run: echo deploy contracts on ropsten
  integration:
    runs-on: ubuntu-latest
    needs: [deployment]
    steps:
      - name: echo
        run: echo run integration tests on ropsten
  tag:
    runs-on: ubuntu-latest
    needs: [integration]
    steps:
      - name: echo
        run: echo increment patch version and tag commit
  publish:
    runs-on: ubuntu-latest
    needs: [tag]
    steps:
      - name: echo
        run: echo publish package to npm and github
