name: Main

on:
  push:
    tags-ignore: [v*.*.*]
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: yarn install --frozen-lockfile
      - run: yarn format:check
      - run: yarn lint:solhint
      - run: yarn lint:eslint

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - run: yarn test:unit # include code coverage
      - run: yarn test:gas

  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - run: sudo add-apt-repository ppa:ethereum/ethereum
      - run: sudo apt update && sudo apt install solc
      - run: pip3 install -r configurations/requirements.txt
      - run: slither contracts/DomainRegistry.sol --print human-summary

  integration:
    runs-on: ubuntu-latest
    needs: [lint, test, security]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - run: yarn deploy --network ropsten
      - run: yarn test:integration --network ropsten
    env:
      INFURA_PROJECT_ID: ${{ secrets.INFURA_PROJECT_ID }}
      ETHEREUM_PRIVATE_KEY: ${{ secrets.ETHEREUM_PRIVATE_KEY }}
      ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}

  publish:
    runs-on: ubuntu-latest
    needs: [integration]
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PEEWEE_TOKEN }}
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org
      - run: yarn install --frozen-lockfile
      - run: git config --global user.email mr@pee.wee && git config --global user.name peewee
      - run: yarn version --patch --message "Increment patch version [skip ci]"
      - run: git push --follow-tags
      - run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
