name: Upgrade

on:
  schedule:
    - cron: 0 0 * * 1-5
  workflow_dispatch:

jobs:
  upgrade:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - run: yarn upgrade
      - run: git add .
      - run: git commit -m "Upgrade packages"
      - run: git push
